# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
# == Variables ==
# 
# You can define here your project Variables.
# If you want to define/override a Variable for a specific Environment, 
# add an additional ‘variables.yaml’ file in a subdirectory in the ‘Config’ folder: 
# '<project>/Config/_<environment>/variables.yaml
#
Variables:
 salesforce-connector:
    auth:
      # Url to the Salesforce user application
      url: https://axonivy-dev-ed.develop.my.salesforce.com/services/data/v64.0
      # Subdomain of the User application
      subdomain: axonivy-dev-ed.develop
      # Consumer Id to authentication
      clientId: 3MVG9YFqzc_KnL.xEifERAJJDMXI_ZJebmFfyso6.35zYxYNYesOGnT5DsEEHvUSKLf0R_uchHqJLodv2mk67
      # Consumer Secret to authentication
      # GrantType
      useAppPermissions: "true"
