# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/rest-clients.json
RestClients:
  SalesforceAPI:
    UUID: a8bd1ef0-7283-4211-9672-3231654ad15f
    Url: ${ivy.var.salesforce-connector.auth.url}
    Icon: res:/webContent/icons/Salesforce-logo.jpg
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - com.axonivy.connector.salesforce.oauth2.OAuth2Feature
    Properties:
      AUTH.baseUri: https://${ivy.var.salesforce-connector.auth.subdomain}.my.salesforce.com/services/oauth2
      AUTH.appId: ${ivy.var.salesforce-connector.auth.clientId}
      AUTH.secretKey: ${ivy.var.salesforce-connector.auth.clientSecret}
      AUTH.useAppPermissions: ${ivy.var.salesforce-connector.auth.useAppPermissions}
