name: CI-Build

on:
  push:
  pull_request:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v6
    secrets:
      mvnArgs: -Dsalesforce.url=${{secrets.URL}} -Dsalesforce.subdomain=${{secrets.SUB_DOMAIN}} -Dsalesforce.clientid=${{secrets.CLIENT_ID}} -Dsalesforce.clientsecret=${{secrets.CLIENT_SECRET}}	
